# -*- coding: utf-8 -*-
"""provaDS2 - marcos vinicius.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ZuDma_WC0VL7bN-SQjNzfG_Td3WLioR
"""

#navio pirata arghh

long_inic = int(input('informe a longitude inicial: '))
long_dest = int(input('informe a longitude de destino: '))
vel = int(input('informe a velocidade (km/h): '))
cont_long = long_inic
cont_dia = 0

while cont_long < long_dest :
  if cont_long == 0 :
    cont_long = long_inic + vel*24/111
  else :
    cont_dia += 1
    cont_long += vel*24/111
    if cont_long > long_dest :
        cont_long = long_dest
    print(f"No final do dia {cont_dia}, a posição do navio é {cont_long:.2f} graus de longitude.")